#!/usr/bin/env python3
"""home-page-moc — generate an Obsidian Map of Content (home-page.md) for a schema wiki.

Deterministic, stdlib-only (no deps). Scans <wiki-root>/wiki/**/*.md and (re)writes
<wiki-root>/home-page.md: an A-Z + Numerals index of every page rendered as
`[[slug]] (singular-category)`, with a compact top jump-bar and `-vs-` mirror entries.

Generic across any wiki that follows the schema's wiki/{concepts,tools,workflows,setup-guides,
causal-chains,metaphors}/ layout — pass the wiki root with --root.

Designed to run as the FINAL step of every ingest so the home page never drifts from the page set.
The output is a build artifact: NEVER hand-edit it — regenerate it.

Rules:
- One section per first character: A-Z (uppercased), then a "Numerals" section for slugs starting
  with a digit. Empty sections are skipped.
- Entries within a section are natural-sorted (so 5 < 8 < 10, not lexical 10 < 5 < 8).
- Category label is the page's parent folder, singularized (concepts->concept, tools->tool,
  workflows->workflow, setup-guides->setup-guide, causal-chains->causal-chain, metaphors->metaphor).
- `-vs-` mirror: a page may carry a `moc_mirror: <slug>` frontmatter field naming the swapped-operand
  form (e.g. functional-vs-conventional-paradigm -> moc_mirror: conventional-vs-functional-paradigm).
  The generator emits a plain-text mirror entry under the mirror's own letter:
  `conventional-vs-functional-paradigm (see [[functional-vs-conventional-paradigm]])`. No string
  algorithm can derive the mirror spelling, so it must be declared on the page.

Usage:
    python home-page-moc.py [--root DIR] [--title "..."]
    (default --root: current directory)
"""
import os, re, sys, json, glob, argparse

SINGULAR = {
    "concepts": "concept", "tools": "tool", "workflows": "workflow",
    "setup-guides": "setup-guide", "causal-chains": "causal-chain", "metaphors": "metaphor",
}


def singular(folder):
    return SINGULAR.get(folder, folder[:-1] if folder.endswith("s") else folder)


def natkey(s):
    """Natural sort key: split into text/number runs so 5 < 8 < 10."""
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", s.lower())]


def read_moc_mirror(path):
    """Return the value of a `moc_mirror:` frontmatter field, or None."""
    try:
        with open(path, encoding="utf-8") as f:
            txt = f.read()
    except OSError:
        return None
    if not txt.startswith("---"):
        return None
    end = txt.find("\n---", 3)
    if end == -1:
        return None
    for line in txt[3:end].splitlines():
        m = re.match(r"\s*moc_mirror\s*:\s*(.+?)\s*$", line)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    return None


def bucket_of(slug):
    c = slug[0]
    if c.isalpha():
        return c.upper()
    return "Numerals"  # digits (and any non-alpha) sort into Numerals


def derive_title(root):
    """Title from index.md's H1 (Index -> Map of Content), else from the root folder name."""
    idx = os.path.join(root, "index.md")
    if os.path.isfile(idx):
        with open(idx, encoding="utf-8") as f:
            for line in f:
                if line.startswith("# "):
                    h = line[2:].strip()
                    h2 = re.sub(r"Index\s*$", "Map of Content", h)
                    return h2 if "Map of Content" in h2 else h + " — Map of Content"
    return os.path.basename(os.path.abspath(root)) + " — Map of Content"


def build(root, title):
    wiki_dir = os.path.join(root, "wiki")
    pages, mirrors = [], []
    for path in glob.glob(os.path.join(wiki_dir, "**", "*.md"), recursive=True):
        slug = os.path.splitext(os.path.basename(path))[0]
        folder = os.path.basename(os.path.dirname(path))
        pages.append((slug, singular(folder)))
        mm = read_moc_mirror(path)
        if mm:
            mirrors.append((mm, slug))

    buckets = {}  # bucket -> list of (sortkey_slug, rendered_line)
    for slug, cat in pages:
        buckets.setdefault(bucket_of(slug), []).append((slug, f"- [[{slug}]] ({cat})"))
    for mslug, real in mirrors:
        buckets.setdefault(bucket_of(mslug), []).append((mslug, f"- {mslug} (see [[{real}]])"))

    letters = [c for c in (chr(i) for i in range(ord("A"), ord("Z") + 1)) if c in buckets]
    sections = letters + (["Numerals"] if "Numerals" in buckets else [])

    jump = " · ".join(f"[[#{s}|{'#' if s == 'Numerals' else s}]]" for s in sections)

    out = [
        "<!-- AUTO-GENERATED by home-page-moc.py — do not edit by hand; regenerated on every ingest. -->",
        "",
        f"# {title}",
        "",
        jump,
        "",
    ]
    for s in sections:
        out.append(f"## {s}")
        for _, line in sorted(buckets[s], key=lambda e: natkey(e[0])):
            out.append(line)
        out.append("")
    out.append(
        f"*{len(pages)} pages across {len(sections)} sections"
        + (f"; {len(mirrors)} -vs- mirror entr{'y' if len(mirrors) == 1 else 'ies'}" if mirrors else "")
        + ". Auto-generated — regenerate with the home-page-moc skill; do not edit by hand.*"
    )
    out.append("")

    dest = os.path.join(root, "home-page.md")
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return dest, len(pages), len(sections), len(mirrors)


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--root", default=".")
    ap.add_argument("--title", default=None)
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    if not os.path.isdir(os.path.join(root, "wiki")):
        print(f"No wiki/ folder under {root}", file=sys.stderr)
        sys.exit(2)

    title = args.title or derive_title(root)
    dest, npages, nsections, nmirrors = build(root, title)
    print("RESULT:" + json.dumps(
        {"home_page": dest, "pages": npages, "sections": nsections, "mirrors": nmirrors},
        ensure_ascii=True,
    ))


if __name__ == "__main__":
    main()
